### ISSUE TITLE
ClassCastException When Upcasting BaseTest Object to Child After First Iteration of DataProvider with TestNG

### ISSUE THREAD

**Issue by row49382** [Magenic/JMAQS#314]
**Summary**
Given using any JMAQS BaseTest implementation for any project, and using the TestNG framework, When a dataprovider is passed into a test using the  `@Test(dataProvider="provider_name")` annotation, the test will successfully be driven for the first iteration, but any following iteration will fail with a ClassCastException when invoking the `getTestObject()` getter method for the `testObject` instance variable.

**To Reproduce**
1. Create a maven project that has the `jmaqs-selenium` dependency:
```xml
 <dependencies>
        <!-- https://mvnrepository.com/artifact/com.magenic.jmaqs.selenium/jmaqs-selenium -->
        <dependency>
            <groupId>com.magenic.jmaqs.selenium</groupId>
            <artifactId>jmaqs-selenium</artifactId>
            <version>2.0.1-SNAPSHOT</version>
        </dependency>
    </dependencies>
```
   
2. Create a test class implementing any BaseTest implementation (I am using BaseSeleniumTest for this reproduction) that has a data provider and test that uses it like so
```java
public class DataProviderTest extends BaseSeleniumTest {

    @DataProvider(name = "Data")
    public static Object[][] data() {
    	return new Object[][] {
		{ "One" },
		{ "Two" },
		{ "Three" }
        };
    }

    @Test(dataProvider = "Data")
    public void testDataProvider(String data) {
	this.getWebDriver().get("http://www.google.com");
        Assert.assertNotNull(data);       
    }
}
```
3. Execute the test

**Expected behavior**
All tests should run successfully. `data` should be asserted as not-null for each iteration

**Actual behavior**
The first test passes asserting that `data` is not null, but the second and third iterations fail to call
`this.getWebDriver()` with this stacktrace (using intellij test runner):

```text
java.lang.ClassCastException: com.magenic.jmaqs.base.BaseTestObject cannot be cast to com.magenic.jmaqs.selenium.SeleniumTestObject

	at com.magenic.jmaqs.selenium.BaseSeleniumTest.getWebDriver(BaseSeleniumTest.java:31)
	at com.magenic.automatedtests.ui.tests.page_elements.DataProviderTest.testDataProvider(DataProviderTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
```
**Additional context**
To rule out issue with intellij test runner, here is the output using maven pointing to this testng.xml file:
```xml
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
<suite name="DataProvider Test">
    <test name="DP Test">
        <classes>
            <class name="DataProviderTest" />
        </classes>
    </test>
</suite>
```
and this cmd:
```
mvn clean test -DsuiteXmlFile=testng.xml
```
results:
```
[ERROR] Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 18.29 s <<< FAILURE! - in TestSuite
[ERROR] com.magenic.automatedtests.ui.tests.page_elements.DataProviderTest.testDataProvider  Time elapsed: 0.006 s  <<< FAILURE!
java.lang.ClassCastException: class com.magenic.jmaqs.base.BaseTestObject cannot be cast to class com.magenic.jmaqs.selenium.SeleniumTestObject (com.magenic.jmaqs.base.BaseTestObject and com.magenic.jmaqs.selenium.SeleniumTestObject are in unnamed module of loader 'app')
        at com.magenic.automatedtests.ui.tests.page_elements.DataProviderTest.testDataProvider(DataProviderTest.java:21)

[ERROR] com.magenic.automatedtests.ui.tests.page_elements.DataProviderTest.testDataProvider  Time elapsed: 0 s  <<< FAILURE!
java.lang.ClassCastException: class com.magenic.jmaqs.base.BaseTestObject cannot be cast to class com.magenic.jmaqs.selenium.SeleniumTestObject (com.magenic.jmaqs.base.BaseTestObject and com.magenic.jmaqs.selenium.SeleniumTestObject are in unnamed module of loader 'app')
        at com.magenic.automatedtests.ui.tests.page_elements.DataProviderTest.testDataProvider(DataProviderTest.java:21)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR] com.magenic.automatedtests.ui.tests.page_elements.DataProviderTest.testDataProvider
[INFO]   Run 1: PASS
[ERROR]   Run 2: DataProviderTest.testDataProvider:21->BaseSeleniumTest.getWebDriver:31 » ClassCast
[ERROR]   Run 3: DataProviderTest.testDataProvider:21->BaseSeleniumTest.getWebDriver:31 » ClassCast
[INFO]
[INFO]
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.715 s
[INFO] Finished at: 2020-05-18T12:07:56-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-test) on project automation-site-tests: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\robertw\source\Java_Projects\BR\JMAQS-Selenium-Demo\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by row49382** [comment]
The root cause for this issue has been identified - In the BaseTest class, there is this call in the \@AfterMethod

```java
@AfterMethod
public void teardown() {
    // removed for brevity

    try (BaseTestObject baseTestObject = this.getTestObject()) {
        // Release logged messages
        this.loggedExceptions.remove(fullyQualifiedTestName);

        // Release the Base Test Object
        this.baseTestObjects.remove(fullyQualifiedTestName, baseTestObject);
    }

    // Create console logger to log subsequent messages
    this.setTestObject(new BaseTestObject(new ConsoleLogger(), fullyQualifiedTestName));
}
```

Here we are replacing the `SeleniumTestObject` with the `BaseTestObject`. We do this in case we need to log issues after teardown. The consequence of this is that when we get to the n+1 iteration of the data provider, there is a `BaseTestObject` set at the fullyQualifiedTestname. 

Now, when we access the baseTestObjects ConcurrentHashMap in this method in the `BaseExtendableTest` class (NOTE: the original type of `baseTestObject` is the `SeleniumTestObject`):

```java
  @Override
  public void setTestObject(BaseTestObject baseTestObject) {
    if (this.baseTestObjects.putIfAbsent(this.getFullyQualifiedTestClassName(), baseTestObject) == null) {
      this.baseTestObjects.replace(this.getFullyQualifiedTestClassName(), baseTestObject);
    }
  }
```

The `baseTestObject` already has a value set using the fullyQuailifiedTestName from the BaseTestObject set in the \@AfterMethod. As such, when we access the `baseTestObject` again, it is of type `BaseTestObject` so when we cast it to type `T` here (in `BaseExtendableTest`): 

```java
  @Override
  public T getTestObject() {
    return (T) super.getTestObject();
  }
```

We get the ClassCastException because the type isn't of type `T`, it's of type `BaseTestObject`

We are now working on a solution.
